feat: 사용자와 팔로우 엔티티 추가
Spring-Study-20210220/inMoongram pull request #1
Opened 2021-06-27 12:05 UTC by murane

사용자, 팔로우 엔티티 베이스 추가

2021-06-27 12:26 UTC, baek0318 commented
Follow entity의 JoinColumn(name="") 부분에서 follower 와 followee 의 이름이 같은것을 수정해주면 좋을것 같습니다
User entity의 mappedBy에서 제가 알기로는 자신을 타고 들어가는 entity가 들어가야 해서 mappedby(user)가 되야할것 같은데 다시한번 확인해주시면 감사하겠습니다

2021-06-27 15:22 UTC, timel2ss approved these changes

2021-06-27 15:22 UTC, timel2ss commented on repository/src/main/java/com/team/user/Follow.java
> +    @JoinColumn(name = "user_id")
`@ManyToOne`이 사용되면 `@Column`은 사용할 수 없다고 합니다.
https://stackoverflow.com/questions/4121485/columns-not-allowed-on-a-manytoone-property
위의 링크에 따르면 `@Column`과 `@JoinColumn`을 합쳐 `@JoinColumn(name = "user_id", nullable = false)` 정도로 수정할 수 있을 것 같습니다.

2021-06-27 15:22 UTC, timel2ss commented on repository/src/main/java/com/team/user/Follow.java
> +    @JoinColumn(name = "user_id")
해당 라인도 마찬가지로 `@JoinColumn(name = "user_id", nullable = false)`로 수정하면 좋을 것 같습니다.
하지만 이러면 추가적인 문제점이 발생합니다. follower와 followee이 가리키는 column이 동일하여 다음과 같은 에러를 발생시킵니다.
`Repeated column in mapping for entity: com.team.user.Follow column: user_id (should be mapped with insert="false" update="false")`
이에 대한 해결로 https://stackoverflow.com/questions/44331694/following-followers-in-spring 의 두 번째 답변을 참고하면 다음과 같이 수정할 수 있을 것 같습니다. (정확한 해답이 맞는지는 모르겠습니다)
`
	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "from_user_id", nullable = false)
    private User follower;
`
`
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "to_user_id", nullable = false)
    private User followee;
`

2021-06-27 15:22 UTC, timel2ss commented on repository/src/main/java/com/team/user/User.java
> +}
다른 package나 test에서도 접근할 수 있도록 public으로 선언하면 좋을 것 같습니다.

2021-06-27 15:23 UTC, timel2ss approved these changes

2021-06-27 15:23 UTC, timel2ss commented on repository/src/main/java/com/team/user/Follow.java
> +    private User follower;
`@ManyToOne`이 사용되면 `@Column`은 사용할 수 없다고 합니다.
https://stackoverflow.com/questions/4121485/columns-not-allowed-on-a-manytoone-property
위의 링크에 따르면 `@Column`과 `@JoinColumn`을 합쳐 `@JoinColumn(name = "user_id", nullable = false)` 정도로 수정할 수 있을 것 같습니다.

2021-06-27 15:25 UTC, timel2ss approved these changes

2021-06-27 15:25 UTC, timel2ss commented on repository/src/main/java/com/team/user/Follow.java
> +    private User followee;
해당 라인도 마찬가지로 `@JoinColumn(name = "user_id", nullable = false)`로 수정하면 좋을 것 같습니다.
하지만 이러면 추가적인 문제점이 발생합니다. follower와 followee이 가리키는 column이 동일하여 다음과 같은 에러를 발생시킵니다.
`Repeated column in mapping for entity: com.team.user.Follow column: user_id (should be mapped with insert="false" update="false")`
이에 대한 해결로 https://stackoverflow.com/questions/44331694/following-followers-in-spring 의 두 번째 답변을 참고하면 다음과 같이 수정할 수 있을 것 같습니다. (정확한 해답이 맞는지는 모르겠습니다)
`
	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "from_user_id", nullable = false)
    private User follower;
`
`
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "to_user_id", nullable = false)
    private User followee;
`

2021-06-27 15:25 UTC, timel2ss commented on repository/src/main/java/com/team/user/User.java
> +}
다른 package나 test에서도 접근할 수 있도록 public으로 선언하면 좋을 것 같습니다.

2021-06-27 15:35 UTC, timel2ss requested changes
위의 세 부분을 다시 한 번 확인해주세요.

2021-06-27 18:10 UTC, murane commented on repository/src/main/java/com/team/user/User.java
> +}
네 public으로 분리했습니다

2021-06-27 18:11 UTC, murane commented on repository/src/main/java/com/team/user/Follow.java
> +    private User followee;
https://stackoverflow.com/questions/28224618/specifying-multiple-one-to-many-relationships-between-tables-in-hibernate
저는 이걸 참고해서 진행해봤습니다

2021-06-27 18:11 UTC, murane commented on repository/src/main/java/com/team/user/Follow.java
> +    private User follower;
네 저도 테스트해보고 알았는데 합쳐서 nullable을 적용할 수 있는지는 몰랐습니다.
반영해서 마무리 하겠습니다.

2021-06-28 01:29 UTC, baek0318 approved these changes
저는 더이상 문제가 없어보입니다

2021-06-28 01:29 UTC, baek0318 commented on repository/src/main/java/com/team/user/Follow.java
> +    private User followee;
제가 명칭이 좀 헷갈려서 그런데 user1이 user2를 팔로우 하면 follower : user1 , followee: user2가 맞나요?

2021-06-28 03:04 UTC, timel2ss approved these changes

2021-06-28 07:22 UTC, murane commented on repository/src/main/java/com/team/user/Follow.java
> +    private User followee;
네 팔로우하는사람과 팔로우 당하는사람 그렇게 의도했습니다.

2021-06-28 07:22 UTC, merged